### ISSUE TITLE
braze-swift-sdk is included?

### ISSUE THREAD

**Issue by MaggyH** [braze-inc/braze-react-sdk#172]
Hi I would like to ask about 

https://github.com/braze-inc/braze-swift-sdk

Could you please let us know you guys can provide this ?

Thanks in advance

**Comment by Bucimis** [comment]
@MaggyH this is on our roadmap and should be complete within 1-2 quarters.

**Comment by hokstuff** [comment]
Hi @MaggyH,

We have released the Braze React Native SDK [version 2.0.0](https://github.com/braze-inc/braze-react-sdk/releases/tag/2.0.0), which uses the new Braze Swift SDK. You can reference [the Changelog](https://github.com/braze-inc/braze-react-sdk/blob/master/CHANGELOG.md#200) and the sample app for migration steps.

Thanks!
