### ISSUE TITLE
[Feature]: News Feed API Access

### ISSUE THREAD

**Issue by swissmanu** [braze-inc/braze-react-sdk#187]
### What problem are you facing?

The current `appboy-react-sdk` does not provide access to the news feed API's (see https://www.braze.com/docs/developer_guide/platform_integration_guides/android/news_feed/integration/ )

### Workarounds

We use an outdated patch that we apply after every install of `appboy-react-sdk`. Unfortunately, this works/worked only for previous versions of the SDK, since the patch was written in Java "back in the days".

Right now, this holds us back from upgrading to the latest SDK version.

Would you be interested in a pull request that contributes the necessary functionality to access news feed API's?

**Comment by wesleyorbin** [comment]
Hi @swissmanu. If you're able to submit a pull request that adds the functionality you require, we'd happy to take a look at it and get it into the SDK.

**Comment by swissmanu** [comment]
thanks for your feedback @wesleyorbin 🙏 i just submitted #189... let me know what you think.

**Comment by hokstuff** [comment]
Hi @swissmanu,

Thanks for submitting the PR! We are currently working on the React Native migration to use [our new Swift SDK](https://github.com/braze-inc/braze-swift-sdk/), and we were curious if you use the default News Feed UI in your application?

For some context, during the Swift migration we will add data model News Feed support (which appears to be a part of your PR), but it will also have some breaking changes such as removing the default NF UI. Also, we are planning an end-of-life for our News Feed product sometime in the future (TBD on timeline), so we're planning the technical side accordingly.

**Comment by hokstuff** [comment]
Thank you for the context! We are planning to integrate the changes in the PR you submitted into our private codebase and release them together with the Braze Swift SDK migration. This way, you will get the requested API functionality alongside the updated Swift bridge under-the-hood.

**Comment by swissmanu** [comment]
sure! use my code however you see fit 👍 
too bad i loose attribution for my contribution, though 🥲

**Comment by hokstuff** [comment]
We'll be sure to call you out in the Changelog for your contribution 😉

**Comment by hokstuff** [comment]
Hi @swissmanu,

We have released the Braze React Native SDK [version 2.0.0](https://github.com/braze-inc/braze-react-sdk/releases/tag/2.0.0), which uses the new Braze Swift SDK and also introduces the requested News Feed APIs. You can reference [the Changelog](https://github.com/braze-inc/braze-react-sdk/blob/master/CHANGELOG.md#200) and the sample app for migration steps.

Thanks!

**Comment by swissmanu** [comment]
thank you so much for the update and the mention in the changelog @hokstuff 🙏
